# Numpy (넘파이) 기초

### Numpy ndarray 개요

**ndarray 생성 np.array()**
- 파이썬의 리스트와 같은 다양한 인자를 입력 받아서 ndarrary로 변환하는 기능을 수행

In [1]:
# 일반적으로 넘파이 별칭으로 np를 사용한다
import numpy as np

In [2]:
list1 = [1, 2, 3]
print("list1:", list1)
print("list1 type:", type(list1))

array1 = np.array(list1)
print("array1:", array1)
print("array1 type:", type(array1))

list1: [1, 2, 3]
list1 type: <class 'list'>
array1: [1 2 3]
array1 type: <class 'numpy.ndarray'>


**ndarray 의 형태(shape)와 차원**
- 생성된 ndarray 배열의 shape 변수는 ndarray의 크기, 즉 행과 열의 수를 '튜플' 형태로 갖고 있으며, 이를 통해 ndarray 배열의 차원까지 알 수 있다
- 다시 말해, ndarray.shape는 ndarray의 차원과 크기를 '튜플' 형태로 나타내 준다

In [3]:
# 1차원 array로 3개의 데이터를 가지고 있음을 뜻함
array1 = np.array([1, 2, 3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

# 2차원 array로 2개의 row와 3개의 column으로 구성
# 즉, 6개의 데이터를 가지고 있음을 뜻함
array2 = np.array([[1, 2, 3],
                  [2, 3, 4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

# 2차원 array로 1개의 row와 3개의 column으로 구성
# 즉, 3개의 데이터를 가지고 있음을 뜻함
array3 = np.array([[1, 2, 3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


**ndarray.ndim을 통해 각 array의 차원을 알 수 있다**

In [4]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


**ndarray 데이터 값 타입**
- ndarray 내의 데이터 타입은 dtype 속성으로 확인할 수 있다
- 숫자 값, 문자열 값, bool 값 등이 모두 가능하다
- ndarray 내의 데이터 타입은 그 연산의 특성상 같은 데이터 타입만 가능하다!!
- ex) 한 개의 ndarray 객체에 int 와 float 가 함께 있을 수 없다

In [5]:
list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)

print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


**만약 다른 데이터 유형이 섞여 있는 리스트를 ndarray로 변경하면, 데이터의 크기가 더 큰 데이터 타입으로 형 변환을 일괄 적용!**

In [6]:
list2 = [1, 2, 'test']
array2 = np.array(list2)    # 정수형 값들이 모두 사이즈가 큰 '문자열'로 변경된다
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)    # 정수형 값들이 모두 사이즈가 큰 '실수형'으로 변경된다
print(array3, array3.dtype)

['1' '2' 'test'] <U11
[1. 2. 3.] float64


**ndarray 내 데이터 값의 타입 변경도 astype() 메소드를 이용해서 할 수 있다**
- 데이터 타입을 변경하는 경우는 대용량 데이터의 ndarray를 만들 때, 메모리를 더 절약하기 위해서 보통 이용한다

In [7]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')   # float 형으로 변경
print(array_float, array_float.dtype)

array_int1= array_float.astype('int32')     # int 형으로 변경
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2= array_float1.astype('int32')    # int 형으로 변경
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


**ndarray에서 axis 기반의 연산함수 수행**
- axis = 0 은 행 방향을 의미
- axis = 1 은 열 방향을 의미

In [8]:
array2 = np.array([[1, 2, 3],
                  [2, 3, 4]])

print(array2.sum())          # 모든 값들을 sum
print(array2.sum(axis = 0))  # 행 방향으로 sum
print(array2.sum(axis = 1))  # 열 방향으로 sum

15
[3 5 7]
[6 9]


**ndarray를 편리하게 생성하기 - arange, zeros, ones**
- 특정 크기와 차원을 가진 ndarray를 연속값이나 0 또는 1로 초기화해 쉽게 생성해야 할 필요가 있는 경우에 사용한다
- 주로 테스트용으로 데이터를 만들거나 대규모의 데이터를 일괄적으로 초기화해야 할 경우에 사용된다

**1. arange() 함수**
- array를 range()로 표현하는 것
- 파이썬 표준 함수인 range()와 유사한 기능을 한다

In [9]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


**2. zeros() 함수**
- 함수 인자로 '튜플' 형태의 shape 값을 입력하면, 모든 값을 0으로 채운 해당 shape를 가진 ndarray를 반환해준다

**3. ones() 함수**
- 함수 인자로 '튜플' 형태의 shape 값을 입력하면, 모든 값을 1로 채운 해당 shape를 가진 ndarray를 반환해준다

##### <참고> 위의 두 함수 모두 dtype을 정해주지 않으면, default로 'float64' 형의 데이터로 ndarray를 채운다

In [10]:
# dtype 을 지정해준 경우
zero_array = np.zeros((3,2), dtype = 'int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

# dtype 을 지정해주지 않은 경우
one_array = np.ones((3, 2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


**ndarray의 shape를 변경하는 reshape()**
- ndarray를 특정 차원 및 크기로 변환한다
- 변환을 원하는 크기를 함수 인자로 부여하면 된다
- reshape() 는 지정된 사이즈로 변경이 불가능하면 오류를 발생시킨다

In [11]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2, 5)  # 2 row x 5 column 의 형태로 2차원 ndarray로 변환
print('array2:\n', array2)

array3 = array1.reshape(5, 2)  # 5 row x 2 column 의 형태로 2차원 ndarray로 변환
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [12]:
# 변환할 수 있는 shape구조를 입력하면 오류 발생!
array1.reshape(4, 3)

ValueError: cannot reshape array of size 10 into shape (4,3)

**<실제로 reshape()를 효율적으로 사용하는 경우>**

**reshape()에 -1 인자값을 부여하여 특정 차원으로 고정된 가변적인 ndarray형태 변환**
- -1 을 인자로 사용하면 원래 ndarray와 호환되는 새로운 shape로 변환해준다

In [13]:
array1 = np.arange(10)
print(array1)

# array1과 호환될 수 있는 '2차원 ndarray'로 변환하되, column axis 크기는 5에 고정하고, row axis 크기를 이에 맞춰 자동으로 변환
# 즉, 2 x 5 형태로 변환
array2 = array1.reshape(-1, 5)
print('array2 shape:', array2.shape)
print('array2:\n', array2)

# array1과 호환될 수 있는 '2차원 ndarray'로 변환하되, row axis 크기는 5로 고정하고, column axis크기는 이에 맞춰 자동으로 변환
# 즉, 5 x 2 형태로 변환 
array3 = array1.reshape(5, -1)
print('array3 shape:', array3.shape)
print('array3:\n', array3)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3 shape: (5, 2)
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


- reshape()는 (-1, 1), (-1,)와 같은 형태로 주로 사용됨
- 1차원 ndarray를 2차원으로 또는 2차원 ndarray를 1차원으로 변환 시 사용

In [14]:
array1 = np.arange(5)

# 1차원 ndarray를 2차원으로 변환하되, column axis크기는 반드시 1 이여야 함 
array2d_1 = array1.reshape(-1, 1)
print("array2d_1 shape:", array2d_1.shape)
print("array2d_1:\n", array2d_1)

# 2차원 ndarray를 1차원으로 변환
array1d = array2d_1.reshape(-1,)
print("array1d shape:", array1d.shape)
print("array1d:\n", array1d)

array2d_1 shape: (5, 1)
array2d_1:
 [[0]
 [1]
 [2]
 [3]
 [4]]
array1d shape: (5,)
array1d:
 [0 1 2 3 4]


In [15]:
# -1 을 적용하여도 변환이 불가능한 형태로의 변환을 요구할 경우 오류 발생
array1 = np.arange(10)
array4 = array1.reshape(-1, 4)

ValueError: cannot reshape array of size 10 into shape (4)

In [16]:
# 반드시 -1 값은 1개의 인자만 입력해야 함 --> 그렇지 않으면 오류 발생
array1.reshape(-1, -1)

ValueError: can only specify one unknown dimension

**nadrray를 tolist() 메소드를 이용해서 리스트 자료형으로 변환**
- print를 이용해서 출력할 때, 시각적으로 더 이해하기 쉽도록 tolist() 메소드를 사용할 수도 있다

In [17]:
array1 = np.arange(8)
array3d = array1.reshape((2, 2, 2))
print('array3d:\n', array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1, 1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1, 1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


### ndarray의 데이터 세트 선택하기 – 인덱싱(Indexing)

**특정 위치의 단일 값 추출**
- 원하는 위치의 인덱스 값을 지정하면, 해당 위치의 데이터가 반환

In [18]:
# 1에서 부터 9 까지의 1차원 ndarray 생성 
array1 = np.arange(start = 1, stop = 10)
print('array1:', array1)

# index는 0 부터 시작하므로, array1[2]는 3번째 index 위치의 데이터 값을 의미
value = array1[2]
print('value:', value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>


- 인덱스 -1 은 맨 뒤의 데이터 값을 의미

In [19]:
print('맨 뒤의 값:', array1[-1], ', 맨 뒤에서 두번째 값:', array1[-2])

맨 뒤의 값: 9 , 맨 뒤에서 두번째 값: 8


- 단일 인덱스를 이용해 ndarray 내의 데이터 값 수정

In [20]:
array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


- 다차원 ndarray에서 단일 값 추출
- 2차원의 경우 콤마(,)로 분리된 row 와 column 위치의 인덱스를 통해 접근 --> [row, column]

In [21]:
array1d = np.arange(start = 1, stop = 10)
array2d = array1d.reshape(3, 3)
print(array2d)

print('(row = 0, col = 0) index 가리키는 값:', array2d[0, 0])
print('(row = 0, col = 1) index 가리키는 값:', array2d[0, 1])
print('(row = 1, col = 0) index 가리키는 값:', array2d[1, 0])
print('(row = 2, col = 2) index 가리키는 값:', array2d[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row = 0, col = 0) index 가리키는 값: 1
(row = 0, col = 1) index 가리키는 값: 2
(row = 1, col = 0) index 가리키는 값: 4
(row = 2, col = 2) index 가리키는 값: 9


**슬라이싱(Slicing)**
- 연속된 인덱스 상의 ndarray를 추출하는 방식
- ':' 기호 사이에 시작 인덱스와 종료 인덱스를 표시하면, '시작 인덱스'부터 '종료 인덱스 - 1' 위치까지 데이터의 ndarray를 반환

In [22]:
array1 = np.arange(start = 1, stop = 10)
print(array1)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3 4 5 6 7 8 9]
[1 2 3]
<class 'numpy.ndarray'>


- ':' 기호 앞에 시작 인덱스를 생략하면, 자동으로 맨 처음 인덱스인 0 으로 간주
- ':' 기호 뒤에 종료 인덱스를 생략하면, 자동으로 맨 마지막 인덱스로 간주
- ':' 기호 앞/뒤에 시작/종료 인덱스를 생략하면, 자동으로 맨 처음/맨 마지막 인덱스로 간주

In [23]:
array1 = np.arange(start = 1, stop = 10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [24]:
array1d = np.arange(start = 1, stop = 10)
array2d = array1d.reshape(3, 3)
print('array2d:\n', array2d)
print()

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

# 2차원 ndarray에서 뒤에 오는 인덱스를 없애면, 1차원 ndarray를 반환
# 즉, array2d[0]과 같이 2차원에서 뒤에 오는 인덱스를 없애면, row 축(axis = 0)의 첫 번째 row ndarray를 반환
print('array2d[0] \n', array2d[0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]
array2d[0] 
 [1 2 3]


**팬시 인덱싱(fancy indexing)**
- 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해, 해당 위치에 있는 데이터의 ndarray를 반환

In [25]:
array1d = np.arange(start = 1, stop = 10)
array2d = array1d.reshape(3, 3)
print(array2d)

array3 = array2d[[0, 1], 2]
print('array2d[[0, 1], 2] => ', array3.tolist())

array4 = array2d[[0, 2], 0:2]
print('array2d[[0, 2], 0:2] => ', array4.tolist())

array5 = array2d[[0, 1]]
print('array2d[[0, 1]] => ', array5.tolist())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[[0, 1], 2] =>  [3, 6]
array2d[[0, 2], 0:2] =>  [[1, 2], [7, 8]]
array2d[[0, 1]] =>  [[1, 2, 3], [4, 5, 6]]


**불린 인덱싱(Boolean indexing)**
- 조건 필터링과 검색을 동시에 할 수 있기 때문에 매우 자주 사용!!
- 특정 조건에 해당하는지 여부인 True/False 값 인덱싱 집합을 기반으로, True에 해당하는 인덱스 위치에 있는 데이터의 ndarray를 반환
- 불린 인덱싱은 ndarray의 인덱스를 지정하는 [ ] 내에 조건문을 그대로 기재하기만 하면 된다

**불린 인덱싱 처리 과정 요약 예시**
- Step 1. array1d > 5 Boolean 조건을 [ ] 내에 입력
- Step 2. False 값은 무시하고, True 값에 해당하는 index 값만 저장
- Step 3. 저장된 index 값으로 데이터 조회

In [26]:
array1d = np.arange(start = 1, stop = 10)
print(array1d)
print(array1d > 5)

var1 = array1d > 5
print("var1:", var1)
print(type(var1))

[1 2 3 4 5 6 7 8 9]
[False False False False False  True  True  True  True]
var1: [False False False False False  True  True  True  True]
<class 'numpy.ndarray'>


In [27]:
# [ ] 안에 array1d > 5 Boolean indexing을 적용 
print(array1d)
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

[1 2 3 4 5 6 7 8 9]
array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [28]:
boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [29]:
indexes = np.array([5, 6, 7, 8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과 :', array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


In [30]:
# 불린 인덱싱을 사용하지 않은 경우(코드가 길어짐)
array1d = np.arange(start = 1, stop = 10)
target = []

for i in range(0, 9):
    if array1d[i] > 5:
        target.append(array1d[i])

array_selected = np.array(target)
print(array_selected)

[6 7 8 9]


In [31]:
print(array1d[array1 > 5])

[6 7 8 9]


### 행렬의 정렬 – sort( )와 argsort( )

**행렬 정렬**

**1. np.sort()**
- 원 행렬은 그대로 유지한 채, 원 행렬의 정렬된 행렬을 반환

**2. ndarray.sort()**
- 원 행렬 자체를 정렬한 형태로 반환하며, 반환 값은 None이다

In [32]:
org_array = np.array([3, 1, 9, 5]) 
print('원본 행렬:', org_array)

# np.sort( )로 정렬 
sort_array1 = np.sort(org_array)         
print ('np.sort( ) 호출 후 반환된 정렬 행렬:', sort_array1) 
print('np.sort( ) 호출 후 원본 행렬:', org_array)

# ndarray.sort( )로 정렬
sort_array2 = org_array.sort()
org_array.sort()
print('org_array.sort( ) 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort( ) 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort( ) 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort( ) 호출 후 원본 행렬: [3 1 9 5]
org_array.sort( ) 호출 후 반환된 행렬: None
org_array.sort( ) 호출 후 원본 행렬: [1 3 5 9]


- np.sort() 와 ndarray.sort() 모두 기본적으로 '오름차순'으로 행렬 내 원소를 정렬
- '내림차순'으로 정렬하기 위해서는 [::-1]을 적용해야 한다!

In [33]:
sort_array1_desc = np.sort(org_array)[::-1]
print ('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


- 행렬이 2차원 이상일 경우, axis 축 값 설정을 통해 row 방향 또는 column 방향으로 정렬을 수행할 수 있다

In [34]:
array2d = np.array([[8, 12], 
                   [7, 1]])

sort_array2d_axis0 = np.sort(array2d, axis = 0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis = 1)
print('컬럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
컬럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


**3. np.argsort()**
- 정렬된 행렬의 '원본 행렬 인덱스'를 ndarray 형으로 반환

In [35]:
org_array = np.array([3, 1, 9, 5]) 
print(np.sort(org_array))

sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

[1 3 5 9]
<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [36]:
# [::-1] 를 사용해서 '내림차순' 정렬된 행렬의 '원본 행렬 인덱스'를 반환하기
org_array = np.array([3, 1, 9, 5]) 
print(np.sort(org_array)[::-1])

sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

[9 5 3 1]
행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


**argsort() 는 넘파이에서 매우 활용도가 높음**
- 넘파이의 데이터 추출에서 많이 사용됨
- ex) 'key-value' 형태의 데이터를 John=78, Mike=95, Sarah=84, Kate=98, Samuel=88 을 ndarray로 만들고, argsort()를 이용하여 key 값을 정렬

In [37]:
name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

# score_array의 정렬된 값에 해당하는 '원본 행렬 위치 인덱스' 반환하고, 이를 이용하여 name_array에서 name 값 추출
sort_indices = np.argsort(score_array)
print('성적 오름차순 정렬시 score_array의 인덱스:', sort_indices)

name_array_sort = name_array[sort_indices]
score_array_sort = score_array[sort_indices]

print('성적 오름차순으로 name_array의 이름 출력:', name_array_sort)
print('성적 오름차순으로 score_array의 점수 출력:', score_array_sort)

성적 오름차순 정렬시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']
성적 오름차순으로 score_array의 점수 출력: [78 84 88 95 98]


### 선형대수 연산 – 행렬 내적과 전치 행렬 구하기

**행렬 내적**
- 두 행렬 A와 B의 내적은 np.dot()을 이용해서 계산이 가능

In [38]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


**전치 행렬**
- 원 행렬에서 행과 열의 위치를 교환한 원소로 구성한 행렬
- 넘파이의 transpose()를 이용해서 쉽게 전치 행렬을 구할 수 있다

In [39]:
A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
